name: Setup
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
        registry-url: https://registry.npmjs.org
        cache: pnpm

    # For provenance https://docs.npmjs.com/generating-provenance-statements#prerequisites
    - name: Install pnpm
      run: npm install -g pnpm
      shell: bash

    - name: Install node modules
      run: pnpm install --frozen-lockfile
      shell: bash
