name: CI

on:
  push:
    branches:
      - main
      - feature/**
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install pnpm
        run: npm install -g pnpm
        shell: bash

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        shell: bash

      - name: Run tests
        run: pnpm test